#:kivy 1.0
#<TimerWidget>

#:set button_font_size 40
#:set label_font_size 60

#:import CyclicRoulette kivy.garden.roulette.CyclicRoulette

<TimerWidget>:
    lbl_temperature: label_temperature
    lbl_timer_value: label_timer_value

    BoxLayout:
        orientation: 'vertical'

        BoxLayout:
            size_hint: (1, .2)
            Button:
                text: "Hauptmenü"
                font_size: button_font_size
                on_release: root.manager.current = "main"
            Button:
                text: "Start"
                font_size: button_font_size
            Button:
                text: "Stop"
                font_size: button_font_size
            Label:
                text: "000 min"
                font_size: button_font_size
                id: label_timer_value
        
        BoxLayout:
            CyclicRoulette:
                cycle: 200
                density: 8.8
                zero_indexed: False
                width: 200
                #on_centered: root.lbl_timer_value.text = str(args[0])
            Label:
                size_hint: (1, .8)
                text: "000.0 °C"
                id: label_temperature
                font_size: 250
            

<MainWidget>:
    lbl_temperature: label_temperature
    lbl_target_temperature: label_target_temperature
    lbl_timer_value: label_timer_value

    BoxLayout:
        orientation: 'vertical'

        BoxLayout:
            size_hint: (1, .2)
            Button:
                text: "Zieltemperatur"
                font_size: button_font_size
            Label:
                id: label_target_temperature
                text: "000.00 °C"
                font_size: label_font_size
            Button:
                text: "Timer stellen"
                font_size: button_font_size
                on_release: root.manager.current = "timer"
            Label:
                text: "000 min"
                font_size: label_font_size
                id: label_timer_value
         
        Label:
            size_hint: (1, .8)
            text: "000.0 °C"
            id: label_temperature
            font_size: 300
            
